# Generated by Django 3.1.4 on 2020-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.FloatField(default='500', max_length=7),
        ),
    ]
