# Generated by Django 3.1.4 on 2020-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201206_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.FloatField(default='500', max_length=3),
        ),
    ]
